### ISSUE TITLE
Add on not available anymore?

### ISSUE THREAD

**Issue by AmandaGeorge** [bplmp/metabase-google-sheets-add-on#2]
It seems the add-on is no longer available through Google, so are you able to update your Readme to give more detail on how to set this up as a Google Apps script?

**Comment by bplmp** [comment]
So this is not the code for an existing add-on, but code that you can adapt to create and publish your own add-on, using these steps: https://developers.google.com/workspace/add-ons/how-tos/publish-add-on-overview. Hope this helps
