### ISSUE TITLE
This action would increase the number of cells in the workbook above the limit of 5000000 cells."

### ISSUE THREAD

**Issue by natea** [bplmp/metabase-google-sheets-add-on#3]
When I try to run the script, I get this error in Google Sheets:

"Question 1 failed to import. Exception: This action would increase the number of cells in the workbook above the limit of 5000000 cells."

I'm tried limiting the number of rows on the Metabase size to 1,000, but I still get this error.

**Comment by bplmp** [comment]
Google sheets has a limit of 5 million cells. If you are limiting rows on Metabase, but still getting this error, it might be that the script is interpreting the results of the query differently from what you see on Metabase.

Maybe you have special characters or linebreaks in your data that are breaking the csv, outputted by Metabase?

I would suggest: 
- go to your metabase query, on metabase
- download the file as a csv
- try importing it manually in Google Sheets or another program, to check if the csv formatting looks OK

**Comment by natea** [comment]
I tried to do the import again and today the report imported with no problem, doing about 6200 rows (not sure about the number of cells).

But thanks for the tip on how to troubleshoot if I get that error again.

Do you know of any way to automate the fetching of data on a schedule (perhaps daily, weekly, monthly)? I'd like to try to avoid having to click the "Import question" button in the Metabase menu.

**Comment by bplmp** [comment]
Good thing it worked!

You can probably use this and adapt thr script to schedule executions:
https://developers.google.com/apps-script/guides/triggers/installable#time-driven_triggers

**Comment by natea** [comment]
I'm getting this error again, and I haven't been able to troubleshoot why it's giving the error. "Question 3 failed to import. Exception: This action would increase the number of cells in the workbook above the limit of 5000000 cells."

I'll try your suggestion of downloading the CSV to see if there are any special characters that are breaking the CSV.

**Comment by natea** [comment]
The only thing I noticed that could potentially cause problems for the import script were some rows in the CSV that have Japanese characters. 
![Screen Shot 2021-05-02 at 10 18 27 AM](https://user-images.githubusercontent.com/118984/116816417-d3ca5f80-ab2f-11eb-9885-afabdd09e497.png)

Do you know if your script can handle these character sets?

**Comment by natea** [comment]
That seemed to solve the problem When I created a filter on the Metabase report to exclude those rows that have content with Japanese characters, then the import worked correctly. Any chance you can make the script support non-ascii characters?

**Comment by bplmp** [comment]
@natea I don't think this is something related to the script... Every part involved seems to support UTF-8 encoding (Metabase, Google Apps Script, etc.).

Again, have you checked if you have line breaks in your data?

**Comment by bplmp** [comment]
![jptxt](https://user-images.githubusercontent.com/11858154/116905593-92ac7b00-ac15-11eb-85c1-766c6eac40a0.gif)

This confirms it works

**Comment by natea** [comment]
Thanks. I'm not sure why it's giving that error then. The error happened with the Japanese characters, and the error went away when I removed them. But since you're clearly able to import text with Japanese characters, it must have been some other reason.

Nate Aune - Founder & CEO, DjangoZoom
http://djangozoom.com | http://twitter.com/djangozoom
+1 (855) DJANGOZOOM
