### ISSUE TITLE
Could not parse text

### ISSUE THREAD

**Issue by ealexisaraujo** [bplmp/metabase-google-sheets-add-on#6]
I received this message, I didn't run the script

![image](https://user-images.githubusercontent.com/9372769/144317945-84f78c16-f6bb-4025-beda-67040a76fc4e.png)

**Comment by Astylia** [comment]
Hey did you find a solution or cause for this ?

**Comment by ealexisaraujo** [comment]
> Hey did you find a solution or cause for this ?

No, nothing!

**Comment by pc-amaral** [comment]
@ealexisaraujo @Astylia I was able to manage this issue in this link here:
https://github.com/bplmp/metabase-google-sheets-add-on/issues/10
